import { useStores } from '../hooks/useStore';
import { observer } from 'mobx-react-lite';
import Head from 'next/head';
import { useEffect } from 'react';
import styles from './Content.module.css';

export const Content = observer(function Content() {
  const {
    notion: { textList, select },
  } = useStores();
  const { notion } = useStores();
  useEffect(() => {
    // document.addEventListener('keydown', listener);
    localStorage.setItem('list', JSON.stringify(textList));
    // return function () {
    //   document.removeEventListener('keydown', listener);
    // };
  });
  // const listener = (e: KeyboardEvent) => {
  //   if (e.key === 'Enter') {
  //     notion.addTextListItem();
  //   }
  // };

  return (
    <>
      <Head>
        <title>Next-test</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {textList.map((textElement, index) => {
        return (
          <div key={index}>
            <select
              onChange={(e) => {
                const value = e.target.value as
                  | 'title h1'
                  | 'text'
                  | 'callout'
                  | 'checkbox';
                notion.changeTextListKind(index, value);
              }}
              defaultValue={textElement.kind}
            >
              {select.map((selectElement, index) => {
                return (
                  <option value={selectElement} key={index}>
                    {selectElement}
                  </option>
                );
              })}
            </select>
            {textElement.kind === 'checkbox' ? (
              <input
                type={textElement.kind}
                onChange={(e) =>
                  notion.changeCheckboxChecked(index, e.target.checked)
                }
                checked={textElement.checked}
              ></input>
            ) : (
              ''
            )}
            <input
              onChange={(e) => {
                notion.changeTextElementValue(index, e.target.value);
              }}
              value={textElement.value}
              onClick={(e) => {
                console.log(e.target);
              }}
              autoFocus={index === 0}
              className={styles.input}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  notion.addTextListItem(index);
                }
              }}
            ></input>
          </div>
        );
      })}
    </>
  );
});
