import { useStores } from '../hooks/useStore';
import { observer } from 'mobx-react-lite';
import Head from 'next/head';
import { useEffect, useState } from 'react';

export const Content = observer(function Content() {
  const {
    notion: { textList, select },
  } = useStores();
  const { notion } = useStores();
  const [key, setkey] = useState(0);
  useEffect(() => {
    localStorage.setItem('list', JSON.stringify(textList));
    document.querySelector<HTMLInputElement>(`#_${key}`)?.focus();
  });

  return (
    <>
      <Head>
        <title>Next-test</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {textList.map((textElement, index) => {
        return (
          <div key={index}>
            <select
              onChange={(e) => {
                const value = e.target.value as
                  | 'title h1'
                  | 'text'
                  | 'callout'
                  | 'checkbox';
                notion.changeTextListKind(index, value);
              }}
              value={textElement.kind}
            >
              {select.map((selectElement, index) => {
                return (
                  <option value={selectElement} key={index}>
                    {selectElement}
                  </option>
                );
              })}
            </select>
            {textElement.kind === 'checkbox' ? (
              <input
                type={textElement.kind}
                onChange={(e) =>
                  notion.changeCheckboxChecked(index, e.target.checked)
                }
                checked={textElement.checked}
              ></input>
            ) : (
              ''
            )}
            <input
              onChange={(e) => {
                notion.changeTextElementValue(index, e.target.value);
              }}
              value={textElement.value}
              // className={`${styles.focus} ${styles[textElement.kind]}`}
              className={`focus ${textElement.kind}`}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  notion.addTextListItem(index);
                  setkey(index + 1);
                }
              }}
              id={`_${index}`}
            ></input>
          </div>
        );
      })}
    </>
  );
});
